### ISSUE TITLE
For phpstan, add option for using phpstan.neon

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/gh-actions-yaml-generator#102]
Add an option with phpstan selection, for using phpstan.neon instead of hardcoded value (like the level).
In file app/Traits/Form/CodeQuality.php:
- [ ] add in public $stepPhpstanUseNeon; // false
- [ ] in loadDefaultsCodeQuality() set as false
- [ ] in loadCodeQualityFromJson set data_fill($j, "stepPhpstanUseNeon", false); for backward compatibility
- [ ] set in setDataCodeQuality function

in resources/views/livewire/form/code-quality.blade.php
- [ ] add a checkbox

in resources/views/yaml/code_quality.blade.php add the case 
```
@if ($stepToolStaticAnalysis == 'phpstan')
```
for the
```
vendor/bin/phpstan analyse {{ $stepDirStaticAnalysis }} --level=4 --no-progress
```
in order to produce something like

```
	    - name: Execute Code Static Analysis (PHP Stan)
      run: |
        vendor/bin/phpstan analyse src --level=4 --no-progress
```
with the option "use phpstan.neon":
```
	    - name: Execute Code Static Analysis (PHP Stan)
      run: |
        vendor/bin/phpstan analyse -c phpstan.neon --no-progress
```

**Comment by roberto-butti** [comment]
Thank you @ActuallyConnor for the great effort and the PR!
I have just one question about blade formatting, just because in the past i had some problem about this.
My comment is: https://github.com/Hi-Folks/gh-actions-yaml-generator/pull/105#issuecomment-938778551

**Comment by ActuallyConnor** [comment]
@roberto-butti I have removed the indentation after your explanation 😃
