### ISSUE TITLE
Feature - Add composer view

### ISSUE THREAD

**Issue by zaratedev** [Hi-Folks/gh-actions-yaml-generator#103]
Hi, great project.

Exploring the project, I think it may be a good idea to add a new composer view for the following data.

```php
$data = [];
$data["title"] = "Ghygen is a GitHub Actions configurator for your Laravel Application.";
$data["description"] = "Setup Database Service, use multiple PHP version, use multiple Laravel versions, build frontend, cache packages, execute Browser, Functional, and Unit tests…";
```

Something like `$view->with(compact('data'))`. Passing the data to the views `configurator.index`, `configurator.about`, `dashboard.index`.

If you like the idea, I can make these changes to participate in the Hacktoberfest challenge.

**Comment by roberto-butti** [comment]
Sure, thank you. I see that honestly there are duplicate codes. I would like to receive pull request for code improvement.
Thank youuu
