### ISSUE TITLE
Add support for PostgreSQL, MS SQL Server and others

### ISSUE THREAD

**Issue by lsnepomuceno** [Hi-Folks/gh-actions-yaml-generator#45]
We love the idea of ​​the project to generate the yml file, it would be interesting to add support for other types of banks besides MySQL.

- [x] PostgreSQL
- [ ] MS SQL Server
- [x] SQLite
- [ ] Mongo or another NoSQL

Thnks!

**Comment by roberto-butti** [comment]
Hi, Thank you for the feedback/suggestion!

I already planned to implement a feature to select : mysql , sqlite, none.
So I'm super happy to know that this thing meets your needs.
I think that i could work on this direction adding also postgresql option. I would like to manage ms sql server and mongo with lower priority.
Anyway your PR is welcome if you want ;)

Thank you!

**Comment by roberto-butti** [comment]
I'm going to close this feature request.
Thanks to this request: sqlite and postgresql are implemented.
So I think that we could consolidate mysql , sqlite and postgresql, and focusing on receiving feedback on those databases.
Probably in the future I could consider to integrate msqlserver unless there is a PR from the community.

Thank you
