### ISSUE TITLE
Add deploy to ploi step

### ISSUE THREAD

**Issue by Glennmen** [Hi-Folks/gh-actions-yaml-generator#74]
Hi,

I am not sure if you are looking for deployment options for this generator but I made the [Ploi Deploy Action](https://github.com/Glennmen/ploi-deploy-action) that triggers the [Ploi.io](https://ploi.io/) webhook or API and deploys your application to the server.

Let me know if you need more information 😄

**Comment by roberto-butti** [comment]
Thank you @Glennmen !!!
For sure this helps me ;)
I was exploring a nice way to add "deploy" step.
As you know, there are many ways to approach deployment. I think your suggestion helps me to focus on Ploi.
This weekend, i'm going to take a deeper look.

**Comment by Glennmen** [comment]
@roberto-butti Great news!
If there are any questions about my ploi action or Ploi in general just let me know 😉

**Comment by roberto-butti** [comment]
thanks to @ashwind-19 we have on develop branch a first approach to deploy via Ploi
https://github.com/Hi-Folks/gh-actions-yaml-generator/tree/develop

**Comment by roberto-butti** [comment]
merged feature, and tagged v0.3.5 .
Thank you @Glennmen  for the initial request and @ashwind-19  for the PR :)
I think that there is room for improvements (like deploy via API and not just via webhook...)
Thank you again!
