### ISSUE TITLE
Support for multiple databases 

### ISSUE THREAD

**Issue by Braunson** [Hi-Folks/gh-actions-yaml-generator#81]
Requesting this as I'm using Laravel's Parallel testing which creates/requires multiple databases. This would likely require one of two things:

1. Multiple services
2. SQL script to be generated separately and called from the MySQL service as a volume

Thoughts?

**Comment by roberto-butti** [comment]
Hi, this morning i was trying parallel testing.
Following the doc: https://laravel.com/docs/8.x/testing#parallel-testing-and-databases
I'm using sqlite database (configured in phpunit.xml)
```
        <server name="DB_CONNECTION" value="sqlite"/>
        <server name="DB_DATABASE" value="test.db"/>
```
launching the command:
```
php artisan test --parallel --processes=4 --recreate-databases
```
with **recreate-databases** option, I see that 4 files (4, like the number of process), are created test.db_test_1, test.db_test_2, test.db_test_3, test.db_test_4.

So I think that we can't do anything on database creation or instance multiple services for parallel testing.
Probably we could create a specific new issue as feature request for "adding parallel option" for testing.
