### ISSUE TITLE
[feature-idea] Generate Actions from Composer.json

### ISSUE THREAD

**Issue by peterfox** [Hi-Folks/gh-actions-yaml-generator#88]
We spoke on Twitter briefly in the week after you pointed out this generator. I was thinking it might be a cool idea if instead of needing to select things via a form that could automate a lot of the option selections using just the info from composer.json?

Detect the PHP version(s), Laravel version etc. and which PHP tools are involved and then just provide a set of appropriate actions to tick. At that point I'd probably even be happy to pay for it as a service if it saved me the time of having to work out which things I could have in my pipeline without the research.

Just a thought anyways.

**Comment by roberto-butti** [comment]
Thank you for the feedback. 
It makes sense, i will follow your suggestion, and I will take a look deeper the composer.json file to detect some configuration.

**Comment by roberto-butti** [comment]
"autodetect":
- [x] name: form composer.json
- [ ] triggers : defaults
- [ ] database: if is laravel and we have some migration files
- [ ] caching : false
- [x] php versions, from composer (detect range via Composer/Semver
- [ ] node install, in packages.json if it is present and detecting version of node from .nvmrc (if it is present)
- [ ] define laravel version: if there is orchestra/testbench in composer.json in require-dev
- [ ] copy env file: if exists .env.example or .env.ci or .env.testing (copy into .env)
- [ ] fix storage permission if the temp directory exists
- [ ] generate key if artisan file and app_key is empty
- [ ] run migrations , same conditions for database
- [ ] phpunit if exists in composer phpunit/phpunit
- [ ] code sniffer if exists in composer
- [ ] codestatic if exists larastan in composer

**Comment by roberto-butti** [comment]
If you want to test a preview, I'm working on **features/88-autogeneration** branch.
