### ISSUE TITLE
[design] New cover png file

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/gh-actions-yaml-generator#92]
Now we have
https://github.com/Hi-Folks/gh-actions-yaml-generator/blob/main/ghygen-github-actions-yaml-generator-laravel.png
as cover image.
![Cover](https://github.com/Hi-Folks/gh-actions-yaml-generator/raw/main/ghygen-github-actions-yaml-generator-laravel.png)

Any suggestion for the new cover ?

**Comment by RoxieElliott** [comment]
I can work on this, any specific design you'd like to see? I could do a background image or different color and clean up the text

**Comment by roberto-butti** [comment]
Hi, 
thank you for your reply.
Honestly, i don't have any "artistic" idea ;)
As you can see, the current cover is not so nice.
Anyway, Ghygen is a tool that aims to **automate** the creation of workflow configuration.
It has also a command line tool to try to **guess** the best configuration that fits your Laravel application.
Some word that i think about GHygen
- **automation**
- **wizard**
- **magic**
- **guess**
- **workflow**

About color, I think about some warm colors.

**Comment by RoxieElliott** [comment]
Great I can work something up!

**Comment by roberto-butti** [comment]
Hi @RoxieElliott  in the meanwhile I created this one. Take a look if you want, what do you think about it ?
https://raw.githubusercontent.com/Hi-Folks/gh-actions-yaml-generator/main/ghygen-github-actions-yaml-generator-laravel.png

**Comment by RoxieElliott** [comment]
I think this one is good too! Here is the final file of the one I made if you like it feel free to use it! I am having difficulty uploading it to replace in a pull request :
![ghygen yaml](https://user-images.githubusercontent.com/91096055/139929770-5f495ea9-0dd7-411e-b3af-91d8e7990829.png)
)
