### ISSUE TITLE
With template "laravelpackage" , avoid cache composer package and vendors

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/gh-actions-yaml-generator#93]
In *resources/templates/json/laravelpackage.json* file are stored default values for Laravel Package template.
I see that in case of Laravel package usually, *composer.lock* file is ignored.
So, we need to change default value in  *resources/templates/json/laravelpackage.json*,
FROM:
```
"stepCacheVendors": true,
"stepCachePackages": true,
```
TO:
```
"stepCacheVendors": false,
"stepCachePackages": false,
```

**Comment by hetpatel33** [comment]
@roberto-butti please review https://github.com/Hi-Folks/gh-actions-yaml-generator/pull/100
